/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PropertyOwnerRouteImport } from './routes/property-owner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyOwnerRoute = PropertyOwnerRouteImport.update({
  id: '/property-owner',
  path: '/property-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/property-owner': typeof PropertyOwnerRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/worker': typeof WorkerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/property-owner': typeof PropertyOwnerRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/worker': typeof WorkerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/property-owner': typeof PropertyOwnerRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/worker': typeof WorkerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/workers': typeof AdminWorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/partners'
    | '/profile'
    | '/property-owner'
    | '/register'
    | '/services'
    | '/worker'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/locations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/partners'
    | '/profile'
    | '/property-owner'
    | '/register'
    | '/services'
    | '/worker'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/locations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/login'
    | '/partners'
    | '/profile'
    | '/property-owner'
    | '/register'
    | '/services'
    | '/worker'
    | '/admin/analytics'
    | '/admin/complaints'
    | '/admin/locations'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  PropertyOwnerRoute: typeof PropertyOwnerRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  WorkerRoute: typeof WorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-owner': {
      id: '/property-owner'
      path: '/property-owner'
      fullPath: '/property-owner'
      preLoaderRoute: typeof PropertyOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWorkersRoute: AdminWorkersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  PropertyOwnerRoute: PropertyOwnerRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  WorkerRoute: WorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
